GET http://localhost:3000/players

###

POST http://localhost:3000/players
content-type: application/json

{
    "player_name":"Dilip",
    "jersey_number":27,
    "role":"all-rounder"
}

###

PUT http://localhost:3000/players/4/
content-type:application/json

{
    "player_name":"Dilip",
    "jersey_number":27,
    "role":"BatsMen"
}
###

DELETE http://localhost:3000/players/2/
